### ISSUE TITLE
No s2boost.dll file

### ISSUE THREAD

**Issue by FreshSoftware4** [Aroidzap/Stranded-2-Boost#5]
I cannot fine a s2boost.dll file that is called the s2boost.decls file, and I cannot find one online anywhere either

**Comment by aroidzap** [comment]
This project does not produce any "s2boost.dll".

**Comment by FreshSoftware4** [comment]
does it require one then? I can't seem to get it to run in Blitz3D, and there's a s2boost.decls file.

**Comment by FreshSoftware4** [comment]
Also, there's no real instructions, so I don't really know in what order this is assembled, or intended to be assembled
